/**
 * True Friends Quiz — UI Text Translations
 * All user-facing strings organized by language.
 */
var UI_TEXT = {
  en: {
    gameTitle: "True Friends Quiz",
    selectLanguage: "Select Language",
    startGame: "Start Game",
    waitingForPlayers: "Waiting for players...",
    minPlayers: "Need at least 3 players to start",
    players: "Players",
    round: "Round",
    of: "of",
    choosingQuestion: "is choosing a question...",
    pickQuestion: "Pick a question for this round!",
    waitingForHost: "is picking a question...",
    answerQuestion: "Choose your answer!",
    waitingForAnswer: "is answering...",
    guessAnswer: "What do you think",
    answered: "answered?",
    waitingForGuesses: "Wait for your friends to guess...",
    youAnswered: "You answered!",
    timeLeft: "Time left",
    seconds: "s",
    reveal: "The answer is...",
    correct: "Correct! 🎉",
    wrong: "Wrong!",
    theAnswerWas: "The answer was",
    points: "points",
    nextRound: "Next Round",
    gameOver: "Game Over!",
    finalScores: "Final Scores",
    playAgain: "Play Again",
    backToMenu: "Back to Menu",
    yourRank: "You finished",
    welcome: "Welcome",
    waitingToStart: "Waiting for the game to start...",
    youAreHost: "You are the host this round!",
    hasAnswered: "has answered",
    everyoneAnswered: "Everyone has answered!",
    place: ["1st", "2nd", "3rd"],
    score: "Score",
    player: "Player",
    host: "Host",
    settings: "Settings",
    rounds: "Rounds",
    roundsPerPlayer: "Rounds per player",
    back: "Back",
    answerTime: "Answer Time",
    waitingForMasterToStart: "Waiting for {name} to start the game",
    currentLanguage: "Current language",
  },
  el: {
    gameTitle: "True Friends Quiz",
    startGame: "Έναρξη Παιχνιδιού",
    waitingForPlayers: "Αναμονή παικτών...",
    minPlayers: "Χρειάζονται τουλάχιστον 3 παίκτες",
    players: "Παίκτες",
    round: "Γύρος",
    of: "από",
    choosingQuestion: "διαλέγει ερώτηση...",
    pickQuestion: "Διάλεξε μια ερώτηση!",
    waitingForHost: "διαλέγει ερώτηση...",
    answerQuestion: "Διάλεξε την απάντησή σου!",
    waitingForAnswer: "απαντάει...",
    guessAnswer: "Τι νομίζεις ότι απάντησε",
    answered: ";",
    waitingForGuesses: "Περίμενε τους φίλους σου...",
    youAnswered: "Απάντησες!",
    timeLeft: "Χρόνος",
    seconds: "δ",
    reveal: "Η απάντηση είναι...",
    correct: "Σωστά! 🎉",
    wrong: "Λάθος!",
    theAnswerWas: "Η σωστή απάντηση ήταν",
    points: "πόντοι",
    nextRound: "Επόμενος Γύρος",
    gameOver: "Τέλος Παιχνιδιού!",
    finalScores: "Τελική Βαθμολογία",
    playAgain: "Παίξε Ξανά",
    backToMenu: "Πίσω στο Μενού",
    yourRank: "Τερμάτισες",
    welcome: "Καλωσήρθες",
    waitingToStart: "Αναμονή για έναρξη...",
    youAreHost: "Είσαι ο host αυτόν τον γύρο!",
    hasAnswered: "απάντησε",
    everyoneAnswered: "Όλοι απάντησαν!",
    place: ["1ος", "2ος", "3ος"],
    score: "Σκορ",
    player: "Παίκτης",
    host: "Host",
    settings: "Ρυθμίσεις",
    rounds: "Γύροι",
    roundsPerPlayer: "Γύροι ανά παίκτη",
    back: "Πίσω",
    answerTime: "Χρόνος Απάντησης",
    waitingForMasterToStart:
      "Αναμονή για τον/την {name} να ξεκινήσει το παιχνίδι",
    currentLanguage: "Τρέχουσα γλώσσα",
  },
  es: {
    gameTitle: "True Friends Quiz",
    startGame: "Iniciar Juego",
    waitingForPlayers: "Esperando jugadores...",
    minPlayers: "Se necesitan al menos 3 jugadores",
    players: "Jugadores",
    round: "Ronda",
    of: "de",
    choosingQuestion: "está eligiendo una pregunta...",
    pickQuestion: "¡Elige una pregunta para esta ronda!",
    waitingForHost: "está eligiendo una pregunta...",
    answerQuestion: "¡Elige tu respuesta!",
    waitingForAnswer: "está respondiendo...",
    guessAnswer: "¿Qué crees que respondió",
    answered: "?",
    waitingForGuesses: "Espera a que tus amigos adivinen...",
    youAnswered: "¡Has respondido!",
    timeLeft: "Tiempo restante",
    seconds: "s",
    reveal: "La respuesta es...",
    correct: "¡Correcto! 🎉",
    wrong: "¡Incorrecto!",
    theAnswerWas: "La respuesta era",
    points: "puntos",
    nextRound: "Siguiente Ronda",
    gameOver: "¡Fin del Juego!",
    finalScores: "Puntuaciones Finales",
    playAgain: "Jugar de Nuevo",
    backToMenu: "Volver al Menú",
    yourRank: "Terminaste en",
    welcome: "Bienvenido",
    waitingToStart: "Esperando para iniciar...",
    youAreHost: "¡Eres el anfitrión en esta ronda!",
    hasAnswered: "ha respondido",
    everyoneAnswered: "¡Todos han respondido!",
    place: ["1º", "2º", "3º"],
    score: "Puntuación",
    player: "Jugador",
    host: "Anfitrión",
    settings: "Ajustes",
    rounds: "Rondas",
    roundsPerPlayer: "Rondas por jugador",
    back: "Volver",
    answerTime: "Tiempo de Respuesta",
    waitingForMasterToStart: "Esperando a que {name} inicie el juego",
    currentLanguage: "Idioma actual",
  },
  fr: {
    gameTitle: "True Friends Quiz",
    startGame: "Lancer le Jeu",
    waitingForPlayers: "En attente de joueurs...",
    minPlayers: "Il faut au moins 3 joueurs",
    players: "Joueurs",
    round: "Manche",
    of: "sur",
    choosingQuestion: "choisit une question...",
    pickQuestion: "Choisis une question pour cette manche !",
    waitingForHost: "choisit une question...",
    answerQuestion: "Choisis ta réponse !",
    waitingForAnswer: "répond...",
    guessAnswer: "Qu'a répondu",
    answered: "selon toi ?",
    waitingForGuesses: "Attends que tes amis devinent...",
    youAnswered: "Tu as répondu !",
    timeLeft: "Temps restant",
    seconds: "s",
    reveal: "La réponse est...",
    correct: "Correct ! 🎉",
    wrong: "Faux !",
    theAnswerWas: "La réponse était",
    points: "points",
    nextRound: "Manche Suivante",
    gameOver: "Fin du Jeu !",
    finalScores: "Scores Finaux",
    playAgain: "Rejouer",
    backToMenu: "Retour au Menu",
    yourRank: "Tu as fini",
    welcome: "Bienvenue",
    waitingToStart: "En attente du lancement...",
    youAreHost: "Tu es l'hôte de cette manche !",
    hasAnswered: "a répondu",
    everyoneAnswered: "Tout le monde a répondu !",
    place: ["1er", "2ème", "3ème"],
    score: "Score",
    player: "Joueur",
    host: "Hôte",
    settings: "Paramètres",
    rounds: "Manches",
    roundsPerPlayer: "Manches par joueur",
    back: "Retour",
    answerTime: "Temps de Réponse",
    waitingForMasterToStart: "En attente de {name} pour lancer le jeu",
    currentLanguage: "Langue actuelle",
  },
  de: {
    gameTitle: "True Friends Quiz",
    startGame: "Spiel starten",
    waitingForPlayers: "Warte auf Spieler...",
    minPlayers: "Mindestens 3 Spieler benötigt",
    players: "Spieler",
    round: "Runde",
    of: "von",
    choosingQuestion: "wählt eine Frage...",
    pickQuestion: "Wähle eine Frage für diese Runde!",
    waitingForHost: "wählt eine Frage...",
    answerQuestion: "Wähle deine Antwort!",
    waitingForAnswer: "antwortet...",
    guessAnswer: "Was denkst du hat",
    answered: "geantwortet?",
    waitingForGuesses: "Warte auf deine Freunde...",
    youAnswered: "Du hast geantwortet!",
    timeLeft: "Verbleibende Zeit",
    seconds: "s",
    reveal: "Die Antwort ist...",
    correct: "Richtig! 🎉",
    wrong: "Falsch!",
    theAnswerWas: "Die Antwort war",
    points: "Punkte",
    nextRound: "Nächste Runde",
    gameOver: "Spiel vorbei!",
    finalScores: "Endstand",
    playAgain: "Nochmal spielen",
    backToMenu: "Zurück zum Menü",
    yourRank: "Du hast Platz belegt",
    welcome: "Willkommen",
    waitingToStart: "Warte auf den Start...",
    youAreHost: "Du bist der Host dieser Runde!",
    hasAnswered: "hat geantwortet",
    everyoneAnswered: "Alle haben geantwortet!",
    place: ["1.", "2.", "3."],
    score: "Punktzahl",
    player: "Spieler",
    host: "Host",
    settings: "Einstellungen",
    rounds: "Runden",
    roundsPerPlayer: "Runden pro Spieler",
    back: "Zurück",
    answerTime: "Antwortzeit",
    waitingForMasterToStart: "Warten auf {name}, das Spiel zu starten",
    currentLanguage: "Aktuelle Sprache",
  },
  tr: {
    gameTitle: "True Friends Quiz",
    startGame: "Oyunu Başlat",
    waitingForPlayers: "Oyuncular bekleniyor...",
    minPlayers: "En az 3 oyuncu gerekli",
    players: "Oyuncular",
    round: "Tur",
    of: "/",
    choosingQuestion: "soru seçiyor...",
    pickQuestion: "Bu tur için bir soru seç!",
    waitingForHost: "soru seçiyor...",
    answerQuestion: "Cevabını seç!",
    waitingForAnswer: "cevaplıyor...",
    guessAnswer: "Sence ne cevapladı",
    answered: "?",
    waitingForGuesses: "Arkadaşların tahmin etsin...",
    youAnswered: "Cevapladın!",
    timeLeft: "Kalan süre",
    seconds: "sn",
    reveal: "Cevap...",
    correct: "Doğru! 🎉",
    wrong: "Yanlış!",
    theAnswerWas: "Doğru cevap",
    points: "puan",
    nextRound: "Sonraki Tur",
    gameOver: "Oyun Bitti!",
    finalScores: "Son Puanlar",
    playAgain: "Tekrar Oyna",
    backToMenu: "Menüye Dön",
    yourRank: "Bitirdin",
    welcome: "Hoş geldin",
    waitingToStart: "Başlaması bekleniyor...",
    youAreHost: "Bu turda ev sahibi sensin!",
    hasAnswered: "cevapladı",
    everyoneAnswered: "Herkes cevapladı!",
    place: ["1.", "2.", "3."],
    score: "Skor",
    player: "Oyuncu",
    host: "Ev Sahibi",
    settings: "Ayarlar",
    rounds: "Turlar",
    roundsPerPlayer: "Oyuncu başına tur",
    back: "Geri",
    answerTime: "Cevap Süresi",
    waitingForMasterToStart: "{name} oyunu başlatması bekleniyor",
    currentLanguage: "Mevcut dil",
  },
  ar: {
    gameTitle: "True Friends Quiz",
    startGame: "ابدأ اللعبة",
    waitingForPlayers: "بانتظار اللاعبين...",
    minPlayers: "يجب أن يكون هناك 3 لاعبين على الأقل",
    players: "اللاعبون",
    round: "جولة",
    of: "من",
    choosingQuestion: "يختار سؤالاً...",
    pickQuestion: "اختر سؤالاً لهذه الجولة!",
    waitingForHost: "يختار سؤالاً...",
    answerQuestion: "اختر إجابتك!",
    waitingForAnswer: "يجيب...",
    guessAnswer: "ماذا تعتقد أجاب",
    answered: "؟",
    waitingForGuesses: "انتظر أصدقاءك ليخمنوا...",
    youAnswered: "لقد أجبت!",
    timeLeft: "الوقت المتبقي",
    seconds: "ث",
    reveal: "الإجابة هي...",
    correct: "صحيح! 🎉",
    wrong: "خطأ!",
    theAnswerWas: "الإجابة كانت",
    points: "نقاط",
    nextRound: "الجولة التالية",
    gameOver: "انتهت اللعبة!",
    finalScores: "النتائج النهائية",
    playAgain: "العب مرة أخرى",
    backToMenu: "العودة للقائمة",
    yourRank: "أنهيت في المركز",
    welcome: "مرحباً",
    waitingToStart: "بانتظار البدء...",
    youAreHost: "أنت المضيف في هذه الجولة!",
    hasAnswered: "أجاب",
    everyoneAnswered: "الجميع أجاب!",
    place: ["الأول", "الثاني", "الثالث"],
    score: "النتيجة",
    player: "لاعب",
    host: "المضيف",
    settings: "الإعدادات",
    rounds: "الجولات",
    roundsPerPlayer: "جولات لكل لاعب",
    back: "رجوع",
    answerTime: "وقت الإجابة",
    waitingForMasterToStart: "بانتظار {name} لبدء اللعبة",
    currentLanguage: "اللغة الحالية",
  },
};
